<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>ZX2SB.Launcher</RootNamespace>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>

    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
    <LangVersion>default</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZX2SB.Common\ZX2SB.Common.vbproj" />
  </ItemGroup>
</Project>