<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>JRenum</AssemblyName>
		<RootNamespace>CLI_Renum</RootNamespace>
		<OutputType>EXE</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<OptionStrict>On</OptionStrict>
		<OptionExplicit>On</OptionExplicit>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\src_lib\ZX2SB_0_Common\ZX2SB_0_Common.vbproj" />
	  <ProjectReference Include="..\..\src_lib\ZX2SB_5_Renumerador\ZX2SB_5_Renumerador.vbproj" />
	</ItemGroup>
</Project>
