<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>JNorZX</AssemblyName>
		<RootNamespace>CLI_NormalizadorZX</RootNamespace>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>

		<OptionStrict>On</OptionStrict>
		<OptionExplicit>On</OptionExplicit>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src_lib\ZX2SB_0_Common\ZX2SB_0_Common.vbproj" />
		<ProjectReference Include="..\..\src_lib\ZX2SB_1_Normalizador\ZX2SB_1_NormalizadorZX.vbproj" />
	</ItemGroup>

</Project>