<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <AssemblyName>LJSemantic</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ZX2SB.Semantic</RootNamespace>
    <OutputType>Library</OutputType>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\ZX2SB_0_Common\ZX2SB_0_Common.vbproj" />
	</ItemGroup>
</Project>
